language: go

go:
  - 1.10.x

install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME/protoc"
  - go get github.com/golang/protobuf/protoc-gen-go
  - go get github.com/golang/mock/gomock
  - go install github.com/golang/mock/mockgen
  - go get google.golang.org/grpc
  - go get github.com/hpcloud/tail
  - go get github.com/stretchr/testify
  - go get github.com/fatih/color
  - go get github.com/abiosoft/ishell
  - go get github.com/spf13/viper

env:
  - PATH=$HOME/protoc/bin:$PATH

before_script:
  - go generate ./...

script:
  - go test -v ./...

notifications:
  email: false
