language: go

go:
  - 1.10.x

install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME/protoc"

env:
  - PATH=$HOME/protoc/bin:$PATH

before_script:
  - make all
  - mkdir dataStoreQPU/client/mocks
  - go generate ./...

script:
  - go test -v ./...

notifications:
  email: false
