language: go

go:
  - 1.10.x

env:
  - DEP_VERSION="0.5.3"

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - pip3 install boto3
  - pip3 install grpcio-tools
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

before_script:
  - go vet ./...

script:
  - make test

notifications:
  email:
    recipients:
      - dimitrios.vasilas@scality.com
    on_success: always
    on_failure: always