version: '3'
services:
  indexqpu_local_1:
    build:
      context: ../
      dockerfile: qpu/server/Dockerfile
    ports:
      - "127.0.0.1:50350:50350"
    command: go run server.go -qpu=iQPU.lind.1.docker
    networks:
      mynetwork:
        aliases:
          - index.ds1.s3
  indexqpu_local_2:
    build:
      context: ../
      dockerfile: qpu/server/Dockerfile
    ports:
      - "127.0.0.1:50351:50351"
    command: go run server.go -qpu=iQPU.lind.2.docker
    networks:
      mynetwork:
        aliases:
          - index.ds2.s3
  indexqpu_sharded_1:
    build:
      context: ../
      dockerfile: qpu/server/Dockerfile
    ports:
      - "127.0.0.1:50352:50352"
    command: go run server.go -qpu=iQPU.dind.1.docker
    networks:
      mynetwork:
        aliases:
          - index1.s3
  indexqpu_sharded_2:
    build:
      context: ../
      dockerfile: qpu/server/Dockerfile
    ports:
      - "127.0.0.1:50353:50353"
    command: go run server.go -qpu=iQPU.dind.2.docker
    networks:
      mynetwork:
        aliases:
          - index2.s3
  dispatchqpu:
    build:
      context: ../
      dockerfile: qpu/server/Dockerfile
    ports:
      - "127.0.0.1:50550:50550"
    command: go run server.go -qpu=dQPU.docker
    depends_on:
      - indexqpu_local_1
      - indexqpu_local_2
      - indexqpu_sharded_1
      - indexqpu_sharded_2
    networks:
      mynetwork:
        aliases:
          - dispatch.s3

networks:
  mynetwork:
    driver: bridge