version: '3'
services:
  antidote:
    image: dvasilas/antidote:proteus
    deploy:
      placement:
        constraints: [node.labels.node0 == true ]
  cloudserver-0:
    image: dvasilas/cloudserver:latest
    environment:
    - REMOTE_MANAGEMENT_DISABLE=1
    - S3BACKEND=mem
    deploy:
      placement:
        constraints: [node.labels.node0 == true ]
  cloudserver-1:
    image: dvasilas/cloudserver:latest
    environment:
    - REMOTE_MANAGEMENT_DISABLE=1
    - S3BACKEND=mem
    deploy:
      placement:
        constraints: [node.labels.node1 == true ]
  cloudserver-2:
    image: dvasilas/cloudserver:latest
    environment:
    - REMOTE_MANAGEMENT_DISABLE=1
    - S3BACKEND=mem
    deploy:
      placement:
        constraints: [node.labels.node2 == true ]
  dsdriver-0:
    image: dvasilas/proteus:swarm
    command: >
        bash -c "./deployment/wait-for-it.sh --host=cloudserver-0 --port=8000 --timeout=0
        && go run ./launcher/launcher.go --qpu=dbdriver --port=50150 --dataset=1/1/1 --db=s3 --endp=cloudserver-0:8000/cloudserver-0:50000"
    depends_on:
      - cloudserver-0
    deploy:
      placement:
        constraints: [node.labels.node0 == true ]
  dsdriver-1:
    image: dvasilas/proteus:swarm
    command: >
        bash -c "./deployment/wait-for-it.sh --host=cloudserver-1 --port=8000 --timeout=0
        && go run ./launcher/launcher.go --qpu=dbdriver --port=50150 --dataset=2/1/1 --db=s3 --endp=cloudserver-1:8000/cloudserver-1:50000"
    depends_on:
      - cloudserver-1
    deploy:
      placement:
        constraints: [node.labels.node1 == true ]
  dsdriver-2:
    image: dvasilas/proteus:swarm
    command: >
        bash -c "./deployment/wait-for-it.sh --host=cloudserver-2 --port=8000 --timeout=0
        && go run ./launcher/launcher.go --qpu=dbdriver --port=50150 --dataset=3/1/1 --db=s3 --endp=cloudserver-2:8000/cloudserver-2:50000"
    depends_on:
      - cloudserver-2
    deploy:
      placement:
        constraints: [node.labels.node2 == true ]
  qpu_index:
    image: dvasilas/proteus:swarm
    command: >
        bash -c "./deployment/wait-for-it.sh --host=dsdriver-0 --port=50150 --timeout=0
        && ./deployment/wait-for-it.sh --host=dsdriver-1 --port=50150 --timeout=0
        && ./deployment/wait-for-it.sh --host=dsdriver-2 --port=50150 --timeout=0
        && go run ./launcher/launcher.go --qpu=index --port=50250 --config=index_1 --endP=antidote:8087 --conns=dsdriver-0:50150/dsdriver-1:50150/dsdriver-2:50150"
    depends_on:
      - dsdriver-0
      - dsdriver-1
      - dsdriver-2
      - antidote
    deploy:
      placement:
        constraints: [node.labels.node0 == true ]
  workload-0:
    image: dvasilas/proteus:swarm
    command: >
        bash -c "./deployment/wait-for-it.sh --host=cloudserver-0 --port=8000 --timeout=0
        && python3 ./proteus-bench/s3/s3client_server.py --port=50050 --s3=http://cloudserver-0:8000 & ./deployment/wait-for-it.sh --host=qpu_index --port=50250 --timeout=0
        && ./deployment/wait-for-it.sh --host=127.0.0.1 --port=50050 --timeout=0
        && go run ./proteus-bench/s3/bench.go -s3=127.0.0.1:50050 -proteus=qpu_index:50250 -bench=preload -data=/go/src/github.com/dvasilas/proteus/proteus-bench/s3/yelpDataset/dataset.json
        && go run ./proteus-bench/s3/bench.go -s3=127.0.0.1:50050 -proteus=qpu_index:50250 -bench=workload"
    environment:
      - QUERY_TYPE=POINT
    depends_on:
      - qpu_index
    deploy:
      placement:
        constraints: [node.labels.node3 == true ]
  workload-1:
    image: dvasilas/proteus:swarm
    command: >
        bash -c "./deployment/wait-for-it.sh --host=cloudserver-1 --port=8000 --timeout=0
        && python3 ./proteus-bench/s3/s3client_server.py --port=50050 --s3=http://cloudserver-1:8000 & ./deployment/wait-for-it.sh --host=qpu_index --port=50250 --timeout=0
        && ./deployment/wait-for-it.sh --host=127.0.0.1 --port=50050 --timeout=0
        && go run ./proteus-bench/s3/bench.go -s3=127.0.0.1:50050 -proteus=qpu_index:50250 -bench=preload -data=/go/src/github.com/dvasilas/proteus/proteus-bench/s3/yelpDataset/dataset.json
        && go run ./proteus-bench/s3/bench.go -s3=127.0.0.1:50050 -proteus=qpu_index:50250 -bench=workload"
    environment:
      - QUERY_TYPE=POINT
    depends_on:
      - qpu_index
    deploy:
      placement:
        constraints: [node.labels.node3 == true ]
  workload-2:
    image: dvasilas/proteus:swarm
    command: >
        bash -c "./deployment/wait-for-it.sh --host=cloudserver-2 --port=8000 --timeout=0
        && python3 ./proteus-bench/s3/s3client_server.py --port=50050 --s3=http://cloudserver-2:8000 & ./deployment/wait-for-it.sh --host=qpu_index --port=50250 --timeout=0
        && ./deployment/wait-for-it.sh --host=127.0.0.1 --port=50050 --timeout=0
        && go run ./proteus-bench/s3/bench.go -s3=127.0.0.1:50050 -proteus=qpu_index:50250 -bench=preload -data=/go/src/github.com/dvasilas/proteus/proteus-bench/s3/yelpDataset/dataset.json
        && go run ./proteus-bench/s3/bench.go -s3=127.0.0.1:50050 -proteus=qpu_index:50250 -bench=workload"
    environment:
      - QUERY_TYPE=POINT
    depends_on:
      - qpu_index
    deploy:
      placement:
        constraints: [node.labels.node3 == true ]
