version: "2"
services:
  antidote1:
    image: antidotedb/antidote:latest
    ports:
      - "127.0.0.1:8087:8087"
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
    networks:
      mynetwork:
        aliases:
          - antidote

networks:
  mynetwork:
    driver: bridge