version: '3'
services:
  s3:
    image: dvasilas/cloudserver
    ports:
      - "8000"
    environment:
    - REMOTE_MANAGEMENT_DISABLE=1

  lb:
    image: zenko/loadbalancer
    ports:
      - "8000:8000"
    environment:
      LISTEN_PORT: 8000
      UPSTREAM_SERVER: s3:8000

  qpu_datastore:
    image: dvasilas/proteus:latest
    ports:
      - "127.0.0.1:50150:50150"
    command: cloudserver-front 8000 datastore.swarm.testing
    environment:
      - DEBUG=true
    depends_on:
      - lb

  qpu_filter:
    image: dvasilas/proteus:latest
    ports:
      - "127.0.0.1:50250:50250"
    command: qpu_datastore 50150 filter.1.docker
    environment:
      - DEBUG=true
    depends_on:
      - qpu_datastore
